#!/bin/bash
# ═══════════════════════════════════════════════════════════════════════════════
# Cowork CLI Bridge - Docker Setup Helper
# Automatically discovers session path and creates .env file
# ═══════════════════════════════════════════════════════════════════════════════

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CLAUDE_SESSIONS="$HOME/Library/Application Support/Claude/local-agent-mode-sessions"

echo "═══════════════════════════════════════════════════════════════════"
echo "  Cowork CLI Bridge - Docker Setup"
echo "═══════════════════════════════════════════════════════════════════"
echo ""

# Find latest session
find_latest_session() {
  find "$CLAUDE_SESSIONS" -type d -name "local_*" -maxdepth 3 2>/dev/null | while read -r dir; do
    if [ -d "$dir/.claude" ]; then
      stat -f "%m %N" "$dir" 2>/dev/null
    fi
  done | sort -rn | head -1 | cut -d' ' -f2-
}

SESSION_PATH=$(find_latest_session)

if [ -z "$SESSION_PATH" ]; then
  echo "Error: No Cowork session found"
  echo "Start a Cowork session first, then run this script again."
  exit 1
fi

echo "Found session: $SESSION_PATH"
echo ""

# Check for API key
if [ -z "${ANTHROPIC_API_KEY:-}" ]; then
  echo "Enter your Anthropic API key (or set ANTHROPIC_API_KEY env var):"
  read -rs API_KEY
  echo ""
else
  API_KEY="$ANTHROPIC_API_KEY"
  echo "Using ANTHROPIC_API_KEY from environment"
fi

# Create .env file
cat > "$SCRIPT_DIR/.env" << EOF
# Generated by setup.sh on $(date)

# Anthropic API Key
ANTHROPIC_API_KEY=$API_KEY

# Session Path (auto-detected)
SESSION_PATH=$SESSION_PATH

# Claude Sessions Base
CLAUDE_SESSIONS_BASE=$CLAUDE_SESSIONS

# Watcher Settings
POLL_INTERVAL=1
LOG_LEVEL=info
EOF

echo "Created .env file"
echo ""

# Initialize bridge folder if needed
BRIDGE_DIR="$SESSION_PATH/outputs/.bridge"
if [ ! -d "$BRIDGE_DIR" ]; then
  echo "Initializing bridge folder..."
  mkdir -p "$BRIDGE_DIR/requests"
  mkdir -p "$BRIDGE_DIR/responses"
  mkdir -p "$BRIDGE_DIR/streams"
  mkdir -p "$BRIDGE_DIR/logs"
  echo '{"status": "ready", "initialized": "'"$(date -Iseconds)"'"}' > "$BRIDGE_DIR/status.json"
  echo "  ✓ Created $BRIDGE_DIR"
  echo ""
fi

echo "═══════════════════════════════════════════════════════════════════"
echo "  Setup Complete!"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "  Start the bridge:"
echo "    cd $SCRIPT_DIR"
echo "    docker compose up -d"
echo ""
echo "  View logs:"
echo "    docker compose logs -f"
echo ""
echo "  Stop the bridge:"
echo "    docker compose down"
echo ""
echo "  Note: If you start a new Cowork session, run this script again"
echo "  to update the SESSION_PATH in .env"
echo ""
